"""Package entrypoint: ``python -m vertex_live_dab_agent``

Starts the FastAPI server using settings from environment variables (or
``.env`` if you load it with python-dotenv).

Usage::

    python -m vertex_live_dab_agent
    python -m vertex_live_dab_agent --api-only
    python -m vertex_live_dab_agent --frontend-only --backend-url http://192.168.1.50:8081 --port 5173
    # or with uvicorn directly:
    uvicorn vertex_live_dab_agent.api.api:app --reload --port 8000
"""
import argparse
import functools
import json
import os
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

import uvicorn

from vertex_live_dab_agent.artifacts.logger import setup_logging
from vertex_live_dab_agent.config import get_config

_VALID_LOG_LEVELS = {"debug", "info", "warning", "error", "critical"}


def _run_frontend_only(host: str, port: int, backend_url: str) -> None:
    """Serve static UI files with a generated config.js API target."""
    static_dir = Path(__file__).resolve().parent.parent / "static"
    api_base = str(backend_url or "").strip().rstrip("/")
    if not api_base:
        raise SystemExit("--backend-url is required when using --frontend-only")

    class FrontendHandler(SimpleHTTPRequestHandler):
        def do_GET(self) -> None:  # noqa: N802 - stdlib handler API
            if self.path.split("?", 1)[0] == "/config.js":
                payload = (
                    "// Generated by python -m vertex_live_dab_agent --frontend-only\n"
                    f"window.__HARNESS_API_BASE__ = {json.dumps(api_base)};\n"
                ).encode("utf-8")
                self.send_response(200)
                self.send_header("Content-Type", "application/javascript; charset=utf-8")
                self.send_header("Content-Length", str(len(payload)))
                self.send_header("Cache-Control", "no-cache")
                self.end_headers()
                self.wfile.write(payload)
                return
            if self.path in {"", "/"}:
                self.path = "/index.html"
            return super().do_GET()

    handler = functools.partial(FrontendHandler, directory=str(static_dir))
    server = ThreadingHTTPServer((host, int(port)), handler)
    print(f"Frontend UI: http://{host}:{port}/index.html")
    print(f"Backend API: {api_base}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nFrontend server stopped.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the Vertex Live DAB Agent API server.")
    parser.add_argument(
        "--api-only",
        action="store_true",
        help="Disable bundled frontend serving and run only backend APIs.",
    )
    parser.add_argument(
        "--serve-frontend",
        action="store_true",
        help="Force bundled frontend serving on, overriding SERVE_FRONTEND.",
    )
    parser.add_argument(
        "--frontend-only",
        action="store_true",
        help="Serve only the static frontend UI and point it at --backend-url.",
    )
    parser.add_argument(
        "--backend-url",
        help="Backend API base URL for --frontend-only, e.g. http://192.168.1.50:8081.",
    )
    parser.add_argument("--host", help="Bind host, overriding API_HOST.")
    parser.add_argument("--port", type=int, help="Bind port, overriding API_PORT.")
    args = parser.parse_args()

    if args.frontend_only and (args.api_only or args.serve_frontend):
        parser.error("--frontend-only cannot be combined with --api-only or --serve-frontend")
    if args.api_only and args.serve_frontend:
        parser.error("--api-only and --serve-frontend cannot be used together")
    if args.frontend_only:
        _run_frontend_only(
            host=args.host or "0.0.0.0",
            port=args.port or 5173,
            backend_url=args.backend_url or "",
        )
        raise SystemExit(0)
    if args.api_only:
        os.environ["SERVE_FRONTEND"] = "false"
    elif args.serve_frontend:
        os.environ["SERVE_FRONTEND"] = "true"
    if args.host:
        os.environ["API_HOST"] = args.host
    if args.port is not None:
        os.environ["API_PORT"] = str(args.port)

    config = get_config()
    setup_logging(config.log_level)
    uvicorn_log_level = config.log_level.lower()
    if uvicorn_log_level not in _VALID_LOG_LEVELS:
        uvicorn_log_level = "info"
    uvicorn.run(
        "vertex_live_dab_agent.api.api:app",
        host=config.api_host,
        port=config.api_port,
        reload=False,
        log_level=uvicorn_log_level,
    )
