"""Package entrypoint: ``python -m vertex_live_dab_agent``

Starts the FastAPI server using settings from environment variables (or
``.env`` if you load it with python-dotenv).

Usage::

    python -m vertex_live_dab_agent
    python -m vertex_live_dab_agent --api-only
    python -m vertex_live_dab_agent --frontend-only --backend-url http://192.168.1.50:8081 --port 5173
    # or with uvicorn directly:
    uvicorn vertex_live_dab_agent.api.api:app --reload --port 8000
"""
import argparse
import functools
import ipaddress
import json
import os
import urllib.error
import urllib.request
import urllib.parse
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

import uvicorn

from vertex_live_dab_agent.artifacts.logger import setup_logging
from vertex_live_dab_agent.config import get_config

_VALID_LOG_LEVELS = {"debug", "info", "warning", "error", "critical"}


def _is_private_host(value: str) -> bool:
    host = str(value or "").strip()
    if not host:
        return False
    if host in {"localhost", "127.0.0.1", "::1"}:
        return True
    try:
        return ipaddress.ip_address(host).is_private
    except ValueError:
        return False


def _warn_on_frontend_only_public_mismatch(backend_url: str) -> None:
    parsed = urllib.parse.urlparse(str(backend_url or "").strip())
    host = str(parsed.hostname or "").strip()
    if parsed.scheme == "https" and not _is_private_host(host):
        return
    print(
        "Warning: frontend-only mode is pointing browsers at "
        f"{backend_url!r}. Public HTTPS deployments behind Cloudflare will fail "
        "if the configured backend URL is private or plain HTTP. Prefer running "
        "the bundled FastAPI app on the public origin, or expose the backend on "
        "a public HTTPS URL and use that instead.",
        flush=True,
    )


def _run_frontend_only(host: str, port: int, backend_url: str) -> None:
    """Serve static UI files with a generated config.js API target."""
    static_dir = Path(__file__).resolve().parent.parent / "static"
    api_base = str(backend_url or "").strip().rstrip("/")
    if not api_base:
        raise SystemExit("--backend-url is required when using --frontend-only")
    _warn_on_frontend_only_public_mismatch(api_base)

    class FrontendHandler(SimpleHTTPRequestHandler):
        def _proxy_to_backend(self) -> None:
            target_url = f"{api_base}{self.path}"
            body = None
            content_length = self.headers.get("Content-Length")
            if content_length:
                body = self.rfile.read(int(content_length))

            headers = {
                key: value
                for key, value in self.headers.items()
                if key.lower() not in {"host", "content-length", "connection", "accept-encoding"}
            }
            request = urllib.request.Request(
                target_url,
                data=body,
                headers=headers,
                method=self.command,
            )
            try:
                with urllib.request.urlopen(request, timeout=60) as response:
                    self.send_response(response.status)
                    for key, value in response.headers.items():
                        if key.lower() in {"connection", "transfer-encoding"}:
                            continue
                        self.send_header(key, value)
                    self.end_headers()
                    while True:
                        chunk = response.read(64 * 1024)
                        if not chunk:
                            break
                        self.wfile.write(chunk)
            except urllib.error.HTTPError as exc:
                self.send_response(exc.code)
                for key, value in exc.headers.items():
                    if key.lower() in {"connection", "transfer-encoding"}:
                        continue
                    self.send_header(key, value)
                self.end_headers()
                self.wfile.write(exc.read())
            except Exception as exc:
                payload = json.dumps({"error": f"Backend proxy failed: {exc}"}).encode("utf-8")
                self.send_response(502)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(payload)))
                self.end_headers()
                self.wfile.write(payload)

        def do_GET(self) -> None:  # noqa: N802 - stdlib handler API
            request_path = self.path.split("?", 1)[0]
            if request_path == "/config.js":
                payload = (
                    "// Generated by python -m vertex_live_dab_agent --frontend-only\n"
                    f"window.__HARNESS_API_BASE__ = {json.dumps(api_base)};\n"
                ).encode("utf-8")
                self.send_response(200)
                self.send_header("Content-Type", "application/javascript; charset=utf-8")
                self.send_header("Content-Length", str(len(payload)))
                self.send_header("Cache-Control", "no-cache")
                self.end_headers()
                self.wfile.write(payload)
                return
            if self.path in {"", "/"}:
                self.path = "/index.html"
                request_path = "/index.html"
            static_path = (static_dir / request_path.lstrip("/")).resolve()
            if not str(static_path).startswith(str(static_dir.resolve())) or not static_path.is_file():
                self._proxy_to_backend()
                return
            return super().do_GET()

        def do_POST(self) -> None:  # noqa: N802 - stdlib handler API
            self._proxy_to_backend()

        def do_OPTIONS(self) -> None:  # noqa: N802 - stdlib handler API
            self._proxy_to_backend()

        def do_PUT(self) -> None:  # noqa: N802 - stdlib handler API
            self._proxy_to_backend()

        def do_DELETE(self) -> None:  # noqa: N802 - stdlib handler API
            self._proxy_to_backend()

    handler = functools.partial(FrontendHandler, directory=str(static_dir))
    server = ThreadingHTTPServer((host, int(port)), handler)
    print(f"Frontend UI: http://{host}:{port}/index.html")
    print(f"Backend API: {api_base}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nFrontend server stopped.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run the Vertex Live DAB Agent API server.")
    parser.add_argument(
        "--api-only",
        action="store_true",
        help="Disable bundled frontend serving and run only backend APIs.",
    )
    parser.add_argument(
        "--serve-frontend",
        action="store_true",
        help="Force bundled frontend serving on, overriding SERVE_FRONTEND.",
    )
    parser.add_argument(
        "--frontend-only",
        action="store_true",
        help="Serve only the static frontend UI and point it at --backend-url.",
    )
    parser.add_argument(
        "--backend-url",
        help=(
            "Backend API base URL for static frontend serving, e.g. http://192.168.1.50:8081. "
            "When provided without --api-only, this runs frontend-only mode."
        ),
    )
    parser.add_argument("--host", help="Bind host, overriding API_HOST.")
    parser.add_argument("--port", type=int, help="Bind port, overriding API_PORT.")
    args = parser.parse_args()

    if args.frontend_only and args.api_only:
        parser.error("--frontend-only cannot be combined with --api-only")
    if args.api_only and args.serve_frontend:
        parser.error("--api-only and --serve-frontend cannot be used together")
    frontend_only = args.frontend_only or bool(args.backend_url and not args.api_only)
    if frontend_only:
        _run_frontend_only(
            host=args.host or "0.0.0.0",
            port=args.port or 5173,
            backend_url=args.backend_url or "",
        )
        raise SystemExit(0)
    if args.api_only:
        os.environ["SERVE_FRONTEND"] = "false"
    elif args.serve_frontend:
        os.environ["SERVE_FRONTEND"] = "true"
    if args.host:
        os.environ["API_HOST"] = args.host
    if args.port is not None:
        os.environ["API_PORT"] = str(args.port)

    config = get_config()
    setup_logging(config.log_level)
    uvicorn_log_level = config.log_level.lower()
    if uvicorn_log_level not in _VALID_LOG_LEVELS:
        uvicorn_log_level = "info"
    uvicorn.run(
        "vertex_live_dab_agent.api.api:app",
        host=config.api_host,
        port=config.api_port,
        reload=False,
        log_level=uvicorn_log_level,
        access_log=str(os.environ.get("API_ACCESS_LOG", "false")).strip().lower() in {"1", "true", "yes", "on"},
        timeout_graceful_shutdown=float(os.environ.get("API_GRACEFUL_SHUTDOWN_TIMEOUT", "1.0")),
    )
