#!/usr/bin/env bash
set -euo pipefail

# Deploy ONLY frontend (static assets) to GCS static website hosting.
# Usage:
#   ./scripts/deploy_frontend_gcs.sh <PROJECT_ID> <BUCKET_NAME> [API_BASE_URL]
# Example:
#   ./scripts/deploy_frontend_gcs.sh my-gcp-project dab-remote-ui-prod https://dab-live-api-xxx.run.app
#
# If API_BASE_URL is omitted, the script tries to auto-detect Cloud Run service URL
# for service name "dab-live-api" in region "asia-south1".

PROJECT_ID="${1:-}"
BUCKET_NAME="${2:-}"
API_BASE_URL="${3:-}"

if [[ -z "$PROJECT_ID" || -z "$BUCKET_NAME" ]]; then
  echo "Usage: $0 <PROJECT_ID> <BUCKET_NAME> [API_BASE_URL]"
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
INDEX_HTML="$ROOT_DIR/static/index.html"
CONFIG_JS_TMP="$(mktemp)"

cleanup() {
  rm -f "$CONFIG_JS_TMP"
}
trap cleanup EXIT

if [[ ! -f "$INDEX_HTML" ]]; then
  echo "Missing file: $INDEX_HTML"
  exit 1
fi

if [[ -z "$API_BASE_URL" ]]; then
  API_BASE_URL="$(gcloud run services describe dab-live-api --region asia-south1 --format='value(status.url)' 2>/dev/null || true)"
fi

API_BASE_URL="${API_BASE_URL%/}"

cat > "$CONFIG_JS_TMP" <<EOF
// Generated by scripts/deploy_frontend_gcs.sh
window.__HARNESS_API_BASE__ = "${API_BASE_URL}";
EOF

echo "[1/7] Set project"
gcloud config set project "$PROJECT_ID"

echo "[2/7] Enable required service"
gcloud services enable storage.googleapis.com

echo "[3/7] Create bucket if not exists"
if ! gcloud storage buckets describe "gs://$BUCKET_NAME" >/dev/null 2>&1; then
  gcloud storage buckets create "gs://$BUCKET_NAME" --location=ASIA-SOUTH1
fi

echo "[4/7] Configure bucket as static website"
gcloud storage buckets update "gs://$BUCKET_NAME" \
  --web-main-page-suffix=index.html \
  --web-error-page=404.html >/dev/null

echo "[5/7] Make objects publicly readable"
gcloud storage buckets add-iam-policy-binding "gs://$BUCKET_NAME" \
  --member=allUsers \
  --role=roles/storage.objectViewer >/dev/null

echo "[6/7] Upload index.html"
gcloud storage cp "$INDEX_HTML" "gs://$BUCKET_NAME/index.html" --cache-control="no-cache"

echo "[7/7] Upload config.js with static API base"
gcloud storage cp "$CONFIG_JS_TMP" "gs://$BUCKET_NAME/config.js" --cache-control="no-cache"

echo
echo "Frontend deployed (only static UI assets)."
echo "Website URL: http://$BUCKET_NAME.storage.googleapis.com/index.html"
echo "Static Harness API base: ${API_BASE_URL:-<empty>}"
echo
echo "No ngrok needed when API_BASE_URL points to a public Cloud Run URL."
